pieces:
  - Pawn:
      symbol_w: ♙
      symbol_b: ♟
      class_path: pieces/pawn.py
  - Rook:
      symbol_w: ♖
      symbol_b: ♜
      class_path: pieces/rook.py
  - Knight:
      symbol_w: ♘
      symbol_b: ♞
      class_path: pieces/knight.py
  - Bishop:
      symbol_w: ♗
      symbol_b: ♝
      class_path: pieces/bishop.py
  - Queen:
      symbol_w: ♕
      symbol_b: ♛
      class_path: pieces/queen.py
  - King:
      symbol_w: ♔
      symbol_b: ♚
      class_path: pieces/king.py

pattern: standard